import itertools

class Player(object):

    newid = itertools.count()
    def __init__(self, player_info):
        self.new_id = next(Player.newid) + 1
        self.player_url = player_info["player_url"]
        self.short_name = player_info["short_name"]
        self.long_name = player_info["long_name"]
        self.player_positions = player_info["player_positions"]
        self.overall = player_info["overall"]
        self.potential = player_info["potential"]
        self.value_eur = player_info["value_eur"]
        self.wage_eur = player_info["wage_eur"]
        self.age = player_info["age"]
        self.dob = player_info["dob"]
        self.height_cm = player_info["height_cm"]
        self.weight_kg = player_info["weight_kg"]
        self.club_name = player_info["club_name"]
        self.club_position = player_info["club_position"]
        self.club_joined = player_info["club_joined"]
        self.nationality_name = player_info["nationality_name"]
        self.preferred_foot = player_info["preferred_foot"]
        self.skill_moves = player_info["skill_moves"]
        self.work_rate = player_info["work_rate"]
        self.release_clause_eur = player_info["release_clause_eur"]
        self.player_traits = player_info["player_traits"]
        self.pace = player_info["pace"]
        self.shooting = player_info["shooting"]
        self.passing = player_info["passing"]
        self.dribbling = player_info["dribbling"]
        self.physic = player_info["physic"]
        self.attacking_crossing = player_info["attacking_crossing"]
        self.attacking_heading_accuracy = player_info["attacking_heading_accuracy"]
        self.skill_dribbling = player_info["skill_dribbling"]
        self.skill_fk_accuracy = player_info["skill_fk_accuracy"]
        self.movement_acceleration = player_info["movement_acceleration"]
        self.movement_sprint_speed = player_info["movement_sprint_speed"]
        self.movement_agility = player_info["movement_agility"]
        self.power_shot_power = player_info["power_shot_power"]
        self.power_jumping = player_info["power_jumping"]
        self.power_stamina = player_info["power_stamina"]
        self.power_strength = player_info["power_strength"]
        self.power_long_shots = player_info["power_long_shots"]
        self.defending_sliding_tackle = player_info["defending_sliding_tackle"]
        self.ls = player_info["ls"]
        self.st = player_info["st"]
        self.rs = player_info["rs"]
        self.lw = player_info["lw"]
        self.lf = player_info["lf"]
        self.cf = player_info["cf"]
        self.rf = player_info["rf"]
        self.rw = player_info["rw"]
        self.lam = player_info["lam"]
        self.cam = player_info["cam"]
        self.ram = player_info["ram"]
        self.lm = player_info["lm"]
        self.lcm = player_info["lcm"]
        self.cm = player_info["cm"]
        self.rcm = player_info["rcm"]
        self.rm = player_info["rm"]
        self.lwb = player_info["lwb"]
        self.ldm = player_info["ldm"]
        self.cdm = player_info["cdm"]
        self.rdm = player_info["rdm"]
        self.rwb = player_info["rwb"]
        self.lb = player_info["lb"]
        self.lcb = player_info["lcb"]
        self.cb = player_info["cb"]
        self.rcb = player_info["rcb"]
        self.rb = player_info["rb"]
        self.gk = player_info["gk"]
        self.player_face_url = player_info["player_face_url"]
        self.club_logo_url = player_info["club_logo_url"]
        self.club_flag_url = player_info["club_flag_url"]
        self.nation_flag_url = player_info["nation_flag_url"]

    def goals_for_top_scorers(self, goals):
        self.goals = goals

    def __repr__(self):
        r = dict(self.__dict__)
        del r["new_id"]
        return "Player " + str(self.new_id) + " : " + str(r)